# Generated by Django 3.2.4 on 2021-07-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/static/person-icon-blue-7560.png', null=True, upload_to='users/'),
        ),
    ]
